[build]
  publish = "build"  # Directory to deploy (output of 'npm run build')
  command = "npm run build"  # Build command

[[redirects]]
  from = "/api/generate-1/*"  # Proxy path for the first backend URL
  to = "http://51.141.75.21/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/api/generate-2/*"  # Proxy path for the second backend URL
  to = "http://20.252.28.54/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/api/generate-3/*"  # Proxy path for the second backend URL
  to = "http://20.171.233.243/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/api/generate-4/*"  # Proxy path for the second backend URL
  to = "http://52.226.49.117/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/api/generate-5/*"  # Proxy path for the second backend URL
  to = "http://20.165.16.129/:splat"
  status = 200
  force = true
